Refactored auth
havicb/Materialistic pull request #1
Opened 2021-03-09 13:49 UTC by havicb

2021-03-09 13:52 UTC, ahavic1 requested changes

2021-03-09 13:52 UTC, ahavic1 commented on app/src/main/java/com/example/hackernews/MainActivity.kt
> +    private fun updateUI() {
Test

2021-03-09 13:52 UTC, ahavic1 commented on app/src/main/java/com/example/hackernews/auth/AuthUser.kt
> +// todo jesam
Remove todos

2021-03-09 13:52 UTC, havicb commented on app/src/main/java/com/example/hackernews/MainActivity.kt
> +    private fun updateUI() {
Aa

2021-03-10 15:53 UTC, ahavic1 approved these changes

2021-03-11 08:20 UTC, merged